// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "Daikon-BE": accounts Resource Client
//
// Command:
// $ goagen
// --design=github.com/Kumi-comb/Daikon-BE/design
// --out=$(GOPATH)\src\github.com\Kumi-comb\Daikon-BE
// --version=v1.3.1

package client

import (
	"bytes"
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// CreateAccountAccountsPayload is the accounts createAccount action payload.
type CreateAccountAccountsPayload struct {
	Password   *string `form:"password,omitempty" json:"password,omitempty" yaml:"password,omitempty" xml:"password,omitempty"`
	ScreenName *string `form:"screenName,omitempty" json:"screenName,omitempty" yaml:"screenName,omitempty" xml:"screenName,omitempty"`
}

// CreateAccountAccountsPath computes a request path to the createAccount action of accounts.
func CreateAccountAccountsPath() string {

	return fmt.Sprintf("/accounts")
}

// アカウントの作成を行う
func (c *Client) CreateAccountAccounts(ctx context.Context, path string, payload *CreateAccountAccountsPayload, contentType string) (*http.Response, error) {
	req, err := c.NewCreateAccountAccountsRequest(ctx, path, payload, contentType)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewCreateAccountAccountsRequest create the request corresponding to the createAccount action endpoint of the accounts resource.
func (c *Client) NewCreateAccountAccountsRequest(ctx context.Context, path string, payload *CreateAccountAccountsPayload, contentType string) (*http.Request, error) {
	var body bytes.Buffer
	if contentType == "" {
		contentType = "*/*" // Use default encoder
	}
	err := c.Encoder.Encode(payload, &body, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	if contentType == "*/*" {
		header.Set("Content-Type", "application/json")
	} else {
		header.Set("Content-Type", contentType)
	}
	return req, nil
}
