// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "Daikon-BE": linkcode Resource Client
//
// Command:
// $ goagen
// --design=github.com/Kumi-comb/Daikon-BE/design
// --out=$(GOPATH)\src\github.com\Kumi-comb\Daikon-BE
// --version=v1.3.1

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// LinkcodeLinkcodePath computes a request path to the linkcode action of linkcode.
func LinkcodeLinkcodePath(uniqueCode string) string {
	param0 := uniqueCode

	return fmt.Sprintf("/linkcode/%s", param0)
}

// リンクコード生成
func (c *Client) LinkcodeLinkcode(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewLinkcodeLinkcodeRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewLinkcodeLinkcodeRequest create the request corresponding to the linkcode action endpoint of the linkcode resource.
func (c *Client) NewLinkcodeLinkcodeRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
