// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "Daikon-BE": Application User Types
//
// Command:
// $ goagen
// --design=github.com/Kumi-comb/Daikon-BE/design
// --out=$(GOPATH)\src\github.com\Kumi-comb\Daikon-BE
// --version=v1.3.1

package client
