consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
host: localhost:8080
info:
  description: API for train delay display widget
  title: Daikon backend system
  version: ""
paths:
  /linkcode/{uniqueCode}:
    get:
      description: リンクコード生成
      operationId: linkcode#linkcode
      parameters:
      - description: Widget unique code
        in: path
        name: uniqueCode
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
      schemes:
      - http
      summary: linkcode linkcode
      tags:
      - linkcode
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
schemes:
- http
swagger: "2.0"
