// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "Daikon-BE": Application Controllers
//
// Command:
// $ goagen
// --design=github.com/Kumi-comb/Daikon-BE/design
// --out=$(GOPATH)\src\github.com\Kumi-comb\Daikon-BE
// --version=v1.3.1

package app

import (
	"context"
	"github.com/goadesign/goa"
	"net/http"
)

// initService sets up the service encoders, decoders and mux.
func initService(service *goa.Service) {
	// Setup encoders and decoders
	service.Encoder.Register(goa.NewJSONEncoder, "application/json")
	service.Encoder.Register(goa.NewGobEncoder, "application/gob", "application/x-gob")
	service.Encoder.Register(goa.NewXMLEncoder, "application/xml")
	service.Decoder.Register(goa.NewJSONDecoder, "application/json")
	service.Decoder.Register(goa.NewGobDecoder, "application/gob", "application/x-gob")
	service.Decoder.Register(goa.NewXMLDecoder, "application/xml")

	// Setup default encoder and decoder
	service.Encoder.Register(goa.NewJSONEncoder, "*/*")
	service.Decoder.Register(goa.NewJSONDecoder, "*/*")
}

// LinkcodeController is the controller interface for the Linkcode actions.
type LinkcodeController interface {
	goa.Muxer
	Create(*CreateLinkcodeContext) error
}

// MountLinkcodeController "mounts" a Linkcode resource controller on the given service.
func MountLinkcodeController(service *goa.Service, ctrl LinkcodeController) {
	initService(service)
	var h goa.Handler

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewCreateLinkcodeContext(ctx, req, service)
		if err != nil {
			return err
		}
		return ctrl.Create(rctx)
	}
	service.Mux.Handle("GET", "/linkcode/:uniqueCode", ctrl.MuxHandler("create", h, nil))
	service.LogInfo("mount", "ctrl", "Linkcode", "action", "Create", "route", "GET /linkcode/:uniqueCode")
}

// StatusController is the controller interface for the Status actions.
type StatusController interface {
	goa.Muxer
	Get(*GetStatusContext) error
}

// MountStatusController "mounts" a Status resource controller on the given service.
func MountStatusController(service *goa.Service, ctrl StatusController) {
	initService(service)
	var h goa.Handler

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewGetStatusContext(ctx, req, service)
		if err != nil {
			return err
		}
		return ctrl.Get(rctx)
	}
	service.Mux.Handle("GET", "/status/:uniqueCode", ctrl.MuxHandler("get", h, nil))
	service.LogInfo("mount", "ctrl", "Status", "action", "Get", "route", "GET /status/:uniqueCode")
}
