// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "Daikon-BE": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/Kumi-comb/Daikon-BE/design
// --out=$(GOPATH)\src\github.com\Kumi-comb\Daikon-BE
// --version=v1.3.1

package app

// Settings media type (default view)
//
// Identifier: appliaction/vnd.settings; view=default
type Settings struct {
	Lines []string            `form:"lines,omitempty" json:"lines,omitempty" yaml:"lines,omitempty" xml:"lines,omitempty"`
	Times []map[string]string `form:"times,omitempty" json:"times,omitempty" yaml:"times,omitempty" xml:"times,omitempty"`
}

// LineInformation media type (default view)
//
// Identifier: application/vnd.line.information; view=default
type LineInformation struct {
	CorporationName *string `form:"CorporationName,omitempty" json:"CorporationName,omitempty" yaml:"CorporationName,omitempty" xml:"CorporationName,omitempty"`
	ID              *string `form:"ID,omitempty" json:"ID,omitempty" yaml:"ID,omitempty" xml:"ID,omitempty"`
	LineName        *string `form:"LineName,omitempty" json:"LineName,omitempty" yaml:"LineName,omitempty" xml:"LineName,omitempty"`
}
